version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Pacific/Auckland"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Pacific/Auckland"
    groups:
      all:
        patterns:
          - "*"
